### ISSUE TITLE
user.groups and user.projects required or optional?

### ISSUE THREAD

**Issue by musicEnfanthen** [dasch-swiss/dsp-tools#104]
According to the `ontology.json` the properties `groups` and `projects` are not required within a User object in the JSON data model: https://github.com/dasch-swiss/dsp-tools/blob/main/knora/dsplib/schemas/ontology.json#L127

However, the docs say, that "A user must be member of at least one project.": https://dasch-swiss.github.io/dsp-tools/dsp-tools-create/#users

Additionally, the `onto_create_ontology.py` assumes that there is a user.group and a user.projects even if a user is given without these optional properties: https://github.com/dasch-swiss/dsp-tools/blob/main/knora/dsplib/utils/onto_create_ontology.py#L161 and https://github.com/dasch-swiss/dsp-tools/blob/main/knora/dsplib/utils/onto_create_ontology.py#L188

There should be a check first if the optional properties exist, like: `if user["groups"] is not None:`

**Comment by irinaschubert** [comment]
Hi @musicEnfanthen , thank you for the report. We fixed it in dsp-tools version 1.6.1 which has just been released. Both projects and groups are optional inside a user. I updated the documentation and the code, so that no error message appears if you leave one (or both) out. I hereby close this issue.

**Comment by musicEnfanthen** [comment]
Thank you @irinaschubert for the fix in #121
